version: '3'

services:
  backend:
    build: .
    volumes:
      - ./:/opt/backend
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file: ./.env
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
volumes:
  postgres_data:
