# Generated by Django 4.0.6 on 2022-07-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0001_initial'),
        ('turma', '0002_turma_qtd_aulas_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='disciplinas_turma',
            field=models.ManyToManyField(to='disciplina.disciplina'),
        ),
    ]
